##################################################
# Binance config
##################################################

exchange:
  name        : binance
  products: 
    - 'BTCTUSD':
       - id : 'BTC-USD'
       - currency:
          - 'BTC'
          - 'USD'
#    - 'ETH-USD':
#       - currency:
#          - 'ETH'
#          - 'USD'
    
  ##### api secrets ######
  apiKey       : '0xxxx2'
  apiSecret    : 'deeeed'


  orderType    : limit
  orderFee     : 0
  
  backfill:
    - enabled  : Yes  
    - period   : 3  #in Days
    - interval : '5m'  #5m Binance supports only few fixed candle intervals

