##################################################
# OldMonk Global config file
##################################################


# Define the interested exchanges here. 
# One primary exchange for trading and as many others in spectator mode
# data from exchanges in spectator mode will be considered for trading decision
exchanges:
#   - 'binance': 
#      role: 'secondary'
#      config: 'config/binance.yml'
   - 'cbpro' : 
      role: 'primary'
      config: 'config/cbpro.yml'
  
# TODO: exchanges specific config should follow a common timing, should be driven by global config  
#  backfill:
#    - enabled  : Yes  
#    - period   : 3  #in Days
#    - interval : '5m'  #5m 

stop_loss:
   enabled: false
   smart: false #track price movement and update stop_loss
   rate : 8 #-3%
  
take_profit:
   enabled: false
   rate: 10 # 10percent

#decision engine

decision:
# model : [ML|simple]
#   model    : ML
#   config   : "config/model/model.hdf5"

   model    : simple
   config   :
      strategy : EMA_RSI
      params : {'rsi': 64, 'ema_s': 30, 'period': 38, 'ema_m': 200, 'ema_l': 120, 'ema_ll': 60}
      #Hall of Fame
      #EMA_RSI: {'rsi': 64, 'ema_s': 30, 'period': 38, 'ema_m': 200, 'ema_l': 120, 'ema_ll': 60}
      #EMA_DEV{'ema_sell_s': 80, 'treshold_pct_buy_l': 1.12, 'ema_buy_s': 125, 'period': 170, 'treshold_pct_sell_s': 0.00, 'ema_buy_l': 30, 'treshold_pct_sell_l': 1.86, 'treshold_pct_buy_s': 0.21, 'ema_sell_l': 190}      
# EMA_DEV ~buy n hold
#"MINMAX" #<buy hold
#"EMA_RSI" #<buy-hold, high fail%
#TRIX_RSI" #very low profit
#TREND_BOLLINGER"
#TREND_RSI"
simulator:
   enabled : true

genetic_optimizer: 
   enabled : true
   N_POP : 2
   N_GEN : 3
   N_MP : 10
   config   :
      strategy : EMA_RSI   
      trading : {}
#EOF

