##################################################
# OldMonk Global config file
##################################################


# Define the interested exchanges here. 
# One primary exchange for trading and as many others in spectator mode
# data from exchanges in spectator mode will be considered for trading decision
exchanges:
#   - 'binance': 
#      role: 'secondary'
#      config: 'config/binance.yml'
   - 'cbpro' : 
      role: 'primary'
      config: 'config/cbpro.yml'
      products:
         - 'BTC-USD':
            fund_max_liquidity : 900 #$$               
            fund_max_per_buy_value : 30 #$100 max per buy
            asset_max_per_trade_size: 1 #per sell asset size max
            asset_min_per_trade_size: 0.0001 #Min asset size to trade with (may come from exch limits or asset limits)
            decision:
               model    : simple
               config   :
                  strategy: EMA_DEV
                  params : {}            
      # products - end
      order_type    : market
      fee     : 
         maker : 0.15 #make fee %
         taker : 0.25 #taker fee %
   #cbpro - end
# exchanges - end

# TODO: exchanges specific config should follow a common timing, should be driven by global config
backfill:
   enabled  : true  
   period   : 30  #in Days
   interval : 300  #300s == 5m 

simulator:
   enabled : true
   backtesting : true
   
genetic_optimizer: 
   enabled : true
   N_POP : 1000
   N_GEN : 100
   N_MP : 30
   strategy : EMA_DEV
ui:
   enabled : false
   port : 8080
   
#EOF