##################################################
# OldMonk Global config file
##################################################


# Define the interested exchanges here. 
# One primary exchange for trading and as many others in spectator mode
# data from exchanges in spectator mode will be considered for trading decision
exchanges:
#   - 'binance': 
#      role: 'secondary'
#      config: 'config/binance.yml'
   - 'cbpro' : 
      role: 'primary'
      config: 'config/cbpro.yml'
  
# TODO: exchanges specific config should follow a common timing, should be driven by global config  
#  backfill:
#    - enabled  : Yes  
#    - period   : 3  #in Days
#    - interval : '5m'  #5m 

stop_loss:
   enabled: true
   smart: false #track price movement and update stop_loss
   rate : 3 #-3%
  
take_profit:
   enabled: false
   rate: 10 # 10percent

#decision engine

decision:
# model : [ML|simple]
#   model    : ML
#   config   : "config/model/model.hdf5"

   model    : simple
   config   :
      strategy : EMA_RSI
      params : #EMA_DEV- {'ema_sell_s': 80, 'treshold_pct_buy_l': 1.1241586847418519, 'ema_buy_s': 125, 'period': 170, 'treshold_pct_sell_s': 0.009145746217821715, 'ema_buy_l': 30, 'treshold_pct_sell_l': 1.8668055789275229, 'treshold_pct_buy_s': 0.2122106716562029, 'ema_sell_l': 190}      
#         period: 120
#         ema_buy_s : 50
#         ema_buy_l : 120
# EMA_DEV ~buy n hold
#"MINMAX" #<buy hold
#"EMA_RSI" #<buy-hold, high fail%
#TRIX_RSI" #very low profit
#TREND_BOLLINGER"
#TREND_RSI"
simulator:
   enabled : true

genetic_optimizer: 
   enabled : true
   config   :
      strategy : EMA_RSI   

#EOF

